### PR TITLE
Check file size

### LINKED ISSUE #112: Prevent the download of files exceeding 20 MB
As [Telegram's documentation](https://core.telegram.org/bots/faq#how-do-i-download-files) states, bots can't download anything larger than 20 MB:

> **How do I download files?**
Use the [getFile](https://core.telegram.org/bots/api#getfile) method. Please note that this will only work with files of up to 20 MB in size.

The download logic should be changed to prevent attempting the download when the file is too big.

Currently, in this scenario, we have the following failure:
```java
com.github.stickerifier.stickerify.telegram.exception.TelegramApiException: Telegram couldn't execute the getFile request
at com.github.stickerifier.stickerify.bot.Stickerify.execute(Stickerify.java:141)
at com.github.stickerifier.stickerify.bot.Stickerify.retrieveFile(Stickerify.java:105)
at com.github.stickerifier.stickerify.bot.Stickerify.answerFile(Stickerify.java:79)
```

### PR DESCRIPTION
**Pull request by MartelliEnrico**
Fixes #112

### CODE REVIEW

File: src/main/java/com/github/stickerifier/stickerify/telegram/model/TelegramFile.java [hunk 1]
```diff
@@ -0,0 +1,9 @@
+package com.github.stickerifier.stickerify.telegram.model;
+
+public record TelegramFile(String fileId, Long fileSize) {
+	private static final long MAX_DOWNLOADABLE_FILE_SIZE_IN_BYTES = 20_000_000;
```
Comment (rob93c) [inline src/main/java/com/github/stickerifier/stickerify/telegram/model/TelegramFile.java:4]:
```suggestion
	private static final long MAX_DOWNLOADABLE_FILE_SIZE_IN_BYTES = 20_000_000L;
```

File: src/main/java/com/github/stickerifier/stickerify/bot/Stickerify.java [hunk 2]
```diff
@@ -1,8 +1,6 @@
 package com.github.stickerifier.stickerify.bot;
 
-import static com.github.stickerifier.stickerify.telegram.Answer.ERROR;
-import static com.github.stickerifier.stickerify.telegram.Answer.FILE_ALREADY_VALID;
-import static com.github.stickerifier.stickerify.telegram.Answer.FILE_READY;
+import static com.github.stickerifier.stickerify.telegram.Answer.*;
```
Comment (rob93c) [inline src/main/java/com/github/stickerifier/stickerify/bot/Stickerify.java:3]: Please use explicit imports

**Review by rob93c — CHANGES_REQUESTED** [review]

**Review by rob93c — APPROVED** [review]
