### PR TITLE
Limit concurrent video conversions

### LINKED ISSUE #133: Limit concurrent video conversions
When the bot receives many concurrent video conversion requests, the FFmpeg process is unable to complete and the code fails with the following errors:
````
﻿[07/08/2023 17:50:30.049 CET] WARN  Stickerify  - Unable to reply to request from user with processed file
﻿com.github.stickerifier.stickerify.telegram.exception.TelegramApiException: The command couldn't complete successfully
﻿at com.github.stickerifier.stickerify.process.ProcessHelper.executeCommand(ProcessHelper.java:30)
﻿at com.github.stickerifier.stickerify.media.MediaHelper.convertWithFfmpeg(MediaHelper.java:362)
﻿at com.github.stickerifier.stickerify.media.MediaHelper.convertToWebm(MediaHelper.java:297)
﻿
[07/08/2023 17:50:30.136 CET] WARN  Stickerify  - Unable to reply to request from user with processed file
﻿com.github.stickerifier.stickerify.telegram.exception.TelegramApiException: java.io.IOException: Cannot run program "ffmpeg": error=11, Resource temporarily unavailable
﻿at com.github.stickerifier.stickerify.process.ProcessHelper.executeCommand(ProcessHelper.java:35)
﻿at com.github.stickerifier.stickerify.media.MediaHelper.convertWithFfmpeg(MediaHelper.java:362)
﻿at com.github.stickerifier.stickerify.media.MediaHelper.convertToWebm(MediaHelper.java:297)

﻿Caused by: java.io.IOException: Cannot run program "ffmpeg": error=11, Resource temporarily unavailable
﻿at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1140)
﻿at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1074)
﻿at com.github.stickerifier.stickerify.process.ProcessHelper.executeCommand(ProcessHelper.java:26)

﻿Caused by: java.io.IOException: error=11, Resource temporarily unavailable
﻿at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
﻿at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:319)
﻿at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:249)
````

To overcome this issue, we must limit the number of concurrent FFmpeg processes.

Note: the issue arose when 45 concurrent requests hit the bot, resulting in 10 failures.

### PR DESCRIPTION
**Pull request by rob93c**
This pull request closes #133 and aims to ease problem determination when converting files.

### CODE REVIEW

**Comment by rob93c** [comment]
Maybe at this point it might be worth to log the `threadId` as well.
Logback doesn't provide a handy way to retrieve the `threadId` but instead it can show the thread name with `%t` / `%thread`: https://logback.qos.ch/manual/layouts.html#relative but virtual threads have an empty name.

To overcome this issue, we can add a custom converter changing Logback's logic to return the id instead of the name:
````java
public class ThreadIdConverter extends ThreadConverter {

    @Override
    public String convert(final ILoggingEvent e) {
        return String.valueOf(Thread.currentThread().threadId());
    }
}
````

File: src/main/java/com/github/stickerifier/stickerify/process/ProcessHelper.java [hunk 1]
```diff
@@ -22,17 +26,23 @@ public final class ProcessHelper {
 	 * </ul>
 	 */
 	public static Process executeCommand(final String[] command) throws TelegramApiException {
+		final var commandName = command[0];
+
 		try {
+			SEMAPHORE.acquire();
 			var process = new ProcessBuilder(command).start();
-			var processExited = process.waitFor(1, MINUTES);
+			var processExited = process.waitFor(2, MINUTES);
```
Comment (MartelliEnrico) [inline src/main/java/com/github/stickerifier/stickerify/process/ProcessHelper.java:34]: I think 2 minutes is too much for a video conversion of only 20MB in size

File: src/test/java/com/github/stickerifier/stickerify/bot/StickerifyTest.java [hunk 2]
```diff
@@ -19,6 +20,7 @@
 import java.net.URLEncoder;
 import java.nio.charset.StandardCharsets;
 
+@ClearTempFiles
```
Comment (MartelliEnrico) [inline src/test/java/com/github/stickerifier/stickerify/bot/StickerifyTest.java:23]: Instead of an extension to clear our temp files, you could create instead one that sets the `'java.io.tmpdir'` system properties, and it could be used alongside the `@TempDir` extension (or it could extend it).

File: src/test/java/com/github/stickerifier/stickerify/media/MediaHelperTest.java [hunk 3]
```diff
@@ -127,67 +125,147 @@ private void assertVideoConsistency(int expectedWidth, int expectedHeight, float
...
 		var document = resources.loadResource("document.txt");
-		TelegramApiException exception = assertThrows(TelegramApiException.class, () -> MediaHelper.convert(document));
 
-		assertThat(exception.getMessage(), is(equalTo("Passed-in file is not supported")));
+		assertThrows(TelegramApiException.class, () -> MediaHelper.convert(document));
+	}
+
+	@Nested
+	@DisplayName("Concurrently convert")
+	@DisabledIfEnvironmentVariable(named = "EXECUTION_ENVIRONMENT", matches = "local")
```
Comment (MartelliEnrico) [inline src/test/java/com/github/stickerifier/stickerify/media/MediaHelperTest.java:200]: If your intention is to only run these tests on Github Workflow, you could use the `CI` env variable, which is already present.

**Review by MartelliEnrico — CHANGES_REQUESTED** [review]

File: src/test/java/com/github/stickerifier/stickerify/bot/StickerifyTest.java (hunk 2 above)
Comment (rob93c) [reply src/test/java/com/github/stickerifier/stickerify/bot/StickerifyTest.java:21]: I implemented a different way to clear temp files within [the last commit](https://github.com/Stickerifier/Stickerify/pull/134/commits/7644a3361debb03c4b38c57304713e3d850a3ed2) but I must say I prefer the previous one.

Please have a look at the changes, I'll revert the commit after that.

File: src/main/java/com/github/stickerifier/stickerify/process/ProcessHelper.java [hunk 4]
```diff
@@ -22,17 +26,23 @@ public final class ProcessHelper {
 	 * </ul>
 	 */
 	public static Process executeCommand(final String[] command) throws TelegramApiException {
+		final var commandName = command[0];
```
Comment (MartelliEnrico) [inline src/main/java/com/github/stickerifier/stickerify/process/ProcessHelper.java:29]: This can be moved lower when it's actually used

File: src/test/java/com/github/stickerifier/stickerify/junit/TempFilesCleanupExtension.java [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+
+	@Override
+	public void afterAll(ExtensionContext context) throws IOException {
+		deleteTempFiles();
+	}
+
+	private static void deleteTempFiles() throws IOException {
+		try (var files = Files.list(Path.of(System.getProperty("java.io.tmpdir")))) {
+			files.filter(Files::isRegularFile)
+					.map(Path::toFile)
```
Comment (MartelliEnrico) [inline src/test/java/com/github/stickerifier/stickerify/junit/TempFilesCleanupExtension.java:27]: This map is not needed, since in the delete method you revert back to a Path object. Instead just use path.getName().toString() inside the filter

**Review by MartelliEnrico — CHANGES_REQUESTED** [review]

**Review by MartelliEnrico — APPROVED** [review]
LGTM
